version: '2'
volumes:
  db:
  # node_modules:
  deps:
  build:

services:
  db:
    image: postgres:9.6.4
    volumes:
      - 'db:/var/lib/postgresql/data'
    environment:
      POSTGRES_PASSWORD: postgres

  app:
    command: elixir --sname server -S mix phx.server
    build:
      context: ./
      dockerfile: Dockerfile.dev
    working_dir: /app
    depends_on:
      - db
    volumes:
      - './:/app'
      - 'deps:/app/deps'
      - 'build:/app/_build'
    environment:
      DATABASE_HOST: db
      HTTP_PORT: 80
      TERM: xterm
    ports:
      - 4001:80

  # webpack:
  #   build:
  #     context: ./
  #     dockerfile: Dockerfile.webpack
  #   command: yarn run watch
  #   restart: always
  #   working_dir: /app
  #   stop_signal: SIGKILL
  #   volumes:
  #     - './:/app'
  #     - 'deps:/app/deps'
  #     - 'node_modules:/app/node_modules'

  # ngrok:
  #   image: wernight/ngrok
  #   ports:
  #     - 4040:4040
  #   environment:
  #     NGROK_PORT: 'app:80'
